version: 0.0
os: linux
files:
  - source: .
    destination: /home/ec2-user/build
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    mode: 755
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStart:
    - location: start.sh
      runas: ec2-user
      timeout: 300

  ApplicationStop:
    - location: stop.sh
      runas: ec2-user
      timeout: 300
